version: '3.8'

services:

  postgres_db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin Console Service
  pgadmin_console:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin_console
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Login email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # Login password for pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

volumes:

  postgres_data: